implement next_move api
Bao-projects/tictactoe-core pull request #12
Opened 2023-08-10 00:25 UTC by BaoThan

the api able to receive the current board status and output the return from best_next_move in tictactoe_core

2023-08-10 00:37 UTC, truongluan303 requested changes

2023-08-10 00:37 UTC, truongluan303 commented on src/routes/board_status.py
> -    """
This is documentation, so keep it. Also add similar documentation for next best move api!

2023-08-10 00:37 UTC, truongluan303 commented on src/routes/best_next_move.py
> +    print(board)
Remove all 'print'

2023-08-10 00:37 UTC, truongluan303 commented on src/routes/helper/responses.py
> +    for_player: Optional[Player]
This is not needed. When the user call the API they already know who this move is for

2023-08-10 00:37 UTC, truongluan303 commented on src/routes/best_next_move.py
> +    return BestNextMoveResult(for_player, next_move).to_flask_response()
Where is the case where the input is invalid?

2023-08-11 06:55 UTC, truongluan303 requested changes
Almost there! Also did you test the changes with Postman?

2023-08-11 06:55 UTC, truongluan303 commented on src/routes/best_next_move.py
> +    if for_player not in ["X", "O"]:
Since we already support non-capitalized chars when we validate the board, we should also accept non-capitalized chars for the player input.
```suggestion
    if for_player.upper() not in ["X", "O"]:
```

2023-08-11 06:55 UTC, truongluan303 commented on src/routes/best_next_move.py
> +    if for_player not in ["X", "O"]:
Here you make sure the player input is valid, how about the board input? We must make sure all inputs are good.

2023-08-11 06:56 UTC, BaoThan commented on src/routes/best_next_move.py
> +    if for_player not in ["X", "O"]:
yes I did

2023-08-11 08:12 UTC, truongluan303 approved these changes

2023-08-11 08:12 UTC, merged